### PR TITLE
Remove ZWSP characters in User Guide

### LINKED ISSUE #81: Remove ZWSP characters from User Guide

### PR DESCRIPTION
**Pull request by izzahaj**

### CODE REVIEW

**Comment by izzahaj** [comment]
Closes #81

**Review by rama-pang — CHANGES_REQUESTED** [review]
Line 146 still has ZWSP.

**Comment by rama-pang** [comment]
Can find all occurrences of ZWSP by copy-pasting the character from [here](https://unicode-table.com/en/200B/) and using Intellij's "Find in Files" feature.

**Review by rama-pang — APPROVED** [review]
LGTM

**Pull request merged**
